### ISSUE TITLE
Linux Support

### ISSUE THREAD

**Issue by danpalmer** [simonbs/Prettier#7]
Hi @simonbs! I'm thinking of using this library for a server side Swift project. I've given it a go and it works great on macOS – super simple to use, worked perfectly – but it looks like there's no Linux support as it uses the Apple distribution of JSC directly.

Would you consider a contribution of Linux support via `JXKit` (https://github.com/jectivex/JXKit)? This would essentially replace the JavaScriptCore layer with one that uses the necessary infrastructure on each platform.

There are a few potential ways of doing this:
1. Adding the JXKit dependency, swapping out JavaScriptCore for it – simplest but introduces an extra dependency on every platform.
2. Adding the JXKit dependency only for Linux, using compiler conditionals in code to swap between implementations – no dependency when not required, less maintainable/understandable, not certain this approach will work.
3. Implementing some sort of backends system where JSC and JXKit are different backends, with different dependencies, and requiring callers to configure the system with one of the implementations – no dependency when not required, but pushes what is arguably an implementation detail on to users of the library.

Personally I'd go for (1), but that's coming from my perspective of wanting this on the server where the dependency will be necessary anyway and the number of dependencies doesn't really impact the codebase much. I realise constraints are different on user devices so open to your thoughts on the options. Of course open to your thoughts on the whole idea too!

**Comment by danpalmer** [comment]
@simonbs hey, just checking in to see what you think. I'm happy to contribute this if you're interested, so all I'm looking for is the go ahead and any guidance/principles you'd like to give as input.

**Comment by simonbs** [comment]
@danpalmer First of, sorry for the late reply and secondly, thanks for opening this issue. It would be great to see the package support more platforms.

I agree with the three options you outline and have a strong preference for the second option.

I'm all up for using JXKit on Linux but I have no interest in including JXKit in my iOS apps. That's an unnecessary dependency when there's a standard framework that can cover Prettier's use case perfectly fine.

Choosing the backend to use on compile time seems to be the best option to me. Thereby we can use JavaScriptCore on iOS while ensuring the package is compatible with Linux.

Is this option OK with you and would you be up for drafting a PR?

**Comment by danpalmer** [comment]
Sounds good, I can draft a PR for this!

> I'm all up for using JXKit on Linux but I have no interest in including JXKit in my iOS apps. That's an unnecessary dependency when there's a standard framework that can cover Prettier's use case perfectly fine.

Just to clarify the behaviour, in case it changes your mind on the solution...

On iOS, no additional JS framework would be included – JXKit would just be a few Swift classes wrapping the platform `JavaScriptCore`. It's only on Linux/Windows where it is a *little* smarter and uses `JavaScriptCore` from elsewhere. That doesn't stop this being an extra dependency for iOS, but it's really just a thin wrapper with a fairly direct translation of the API.

What do you think? Still prefer option 2?

**Comment by danpalmer** [comment]
@simonbs I've started drafting this, and it seems the APIs between JSContext/JSValue and JXContext/JXValue are close but different in a way that makes it annoying to share code. My approach so far has been to typealias the JX* versions and add extensions for compatibility, but it's not going well.

The main reason it's not going well is that the JXKit API is just "better" and more Swift-y than the JSContext API – unsurprising given the latter is Objective-C. It's things like use of `throw`, using `Decoder`s for turning values into useful types, etc.

I think my next approach would be to create the classes `PrettierContext`/`PrettierValue`, and fully re-implement the necessary API surface (only 2-3 methods each with very close translations), exposing a more Swift-native API to the rest of the library, and then just have two implementations of those classes depending on what can be imported.

...which leads me to think... actually option 1 feels like the right choice, because that's pretty much what JXKit _is_.

Given that it's just a wrapping layer, there's no additional runtime dependency, everything is decided at compile time, I think this still meets all your requirements other than the extra library which should incur minimal overhead.

**Comment by simonbs** [comment]
I'm unsure what the best way forward is here. I've had a closer look at JXKit and I'm not very fond of adding it as a dependency. It doesn't seem to have much traction and the Jective organization it is hosted under is filled with dead links.

The Swift-y interface is a "nice to have" in my opinion and I don't care much about it. On the other hand, I have strong opinions on including a dependency in a package that otherwise have no dependencies but the JavaScript it is wrapping.

I fear what introducing this dependency will mean in terms of maintenance going forward, and personally I have no interest in maintaining a variant of this package that builds heavily on JXKit.

**Comment by danpalmer** [comment]
Thanks for having a think about this. I have had similar concerns about the Jective organisation, but the continued activity on JXKit over a number of years and the multiple maintainers convinced me it was reasonable to use. There seem to be at least 2 frequent contributors.

I've got 2 alternative suggestions...
1. Simplest option, I fork the repo and maintain a version for the long term (or as long as I can) that has cross platform support at the cost of the extra dependency – I'd update the readme to explain the difference.
2. (Preferred?) We duplicate the `Prettier` target in this package as `PrettierCrossPlatform` or something similar.
   - Only the new package has the JXKit dependency.
   - Plugins etc are the same and continue to be updated as normal.
   - Some shared code that is not JXKit dependent could be pulled out into a `PrettierCore` package?
   - Both the plugin API and the public API appear stable and should incur minimal overhead for future changes.
   - API drift would be generally safe and maintenance would not need to happen in lockstep.

I think 2 may be the best of both worlds. You and other iOS engineers don't need to ship an extra dependency. As maintainer you can mostly focus on plugins, keeping core things up to date, and evolving the JSC based API. Breaking changes are unlikely given the stability of this package, and I'm happy to help fix the JXKit package if necessary in the future.

**Comment by simonbs** [comment]
> I think 2 may be the best of both worlds. You and other iOS engineers don't need to ship an extra dependency. As maintainer you can mostly focus on plugins, keeping core things up to date, and evolving the JSC based API. Breaking changes are unlikely given the stability of this package, and I'm happy to help fix the JXKit package if necessary in the future.

I agree with this and think that the second approach is probably the way to go.

**Comment by danpalmer** [comment]
Sorry for the radio silence here, it's been a busy few weeks. I'm still planning to do this, hopefully will have some progress in the next week or two.

**Comment by danpalmer** [comment]
Apologies for the long delay again, this was all motivated by a hobby project that I'm only doing a few hours of a week.

I've decided to go a different route and just use JXKit directly in my own project. I needed the same approach as this package takes for some other JS code, and realised that building my own thin layer on JXKit (for its Linux support and more Swift-y API than raw JavaScriptCore) was the most straightforward option. It means managing my own JS bundle, but I'm already doing that for other things anyway.

I'm sorry this means I won't be able to contribute Linux support here, but I know that was only something @simonbs was open to, not a roadmap feature, so hopefully this won't be a problem. Thanks @simonbs for the input on the journey here, I think we did get to a good solution, just one that I realised wasn't what I actually needed anymore.

For anyone else finding this in the future...
- If you need Linux support here for other packages as well as Prettier, I'd suggest just doing what I did with JXKit directly.
- If you need cross-platform JSC based Prettier, then I'd resurrect the ideas in this issue, I spent time prototyping and I think the final approach we decided on above is the best way to go.
- If you only need Linux support for Prettier, tricky one, but it's probably easiest to use JXKit and bundle your own Prettier with Rollup or something, then at least there's one fewer layers to get through for updates and the maintenance cost on this repo is lower.
