### ISSUE TITLE
swift language support

### ISSUE THREAD

**Issue by mesqueeb** [simonbs/Prettier#9]
I'm looking for a formatter similar to prettier that can run when I save my code in Xcode.

Currently using https://github.com/nicklockwood/SwiftFormat

And it's close, but there's more freedom than with prettier, so I rather have prettier format my swift code for me.

Is this something you could make possible? 😍

**Comment by simonbs** [comment]
This framework is a wrapper around [the code formatter of the same name](https://prettier.io) and [their Swift plugin was deprecated in 2022](https://github.com/prettier/plugin-swift) so I do not have any plans to support it.
